### ISSUE TITLE
Beacon API

### ISSUE THREAD

**Issue by ritter** [snowplow/snowplow-gtm-custom-template-settings#4]
https://snowplowanalytics.com/blog/2019/01/23/snowplow-javascript-tracker-2-10-0-released-with-global-contexts/#beacon-api

beacon seems to be missing from the settings passed to the javascript tracker.

**Comment by paulboocock** [comment]
Beacon is available in the template. It is set in the dispatching settings:
<img width="367" alt="Screenshot 2021-01-09 at 21 28 46" src="https://user-images.githubusercontent.com/8820009/104109020-be4fd200-52c1-11eb-8a30-ee913e86de40.png">
